name: FlyController
main: cn.whohh.fly.FlyPlugin
version: 1.4.4
api-version: 1.20
folia-supported: true
commands:
  fly:
    description: 飞行控制
    usage: /fly [player|all|reload|help]
    tab-completer: cn.whohh.fly.FlyTabCompleter
logging: 
  format: '§7[§3%level%§7] §r%msg%'
  level: INFO
permissions:
  fly.toggle:
    description: 开启飞行
    default: op
  fly.others:
    description: 切换玩家飞行
    default: op
  fly.bypass:
    description: 跳过世界限制
    default: op
  fly.reload:
    description: 重载配置文件
    default: op
  fly.join:
    description: 在进入服务器时开启飞行
    default: op
  fly.all:
    description: 为所有玩家开启飞行
    default: op